name: setup some useful env duing the build
description: detect and setup env $BUILD_NUMBER, $BRANCH

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        REF=${GITHUB_REF##*/}
        BRANCH="${{env.BRANCH}}"
        BRANCH=${BRANCH:-${REF}}
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV

        BUILD_NUMBER="${{env.BUILD_NUMBER}}"
        [ -z "$BUILD_NUMBER" ] && BUILD_NUMBER=${{github.run_number}}
        echo "123 $BUILD_NUMBER"
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

        VERSIONSTR="${{env.VER_NUMBER}}.${{env.BUILD_NUMBER}}"
        echo "VERSIONSTR=$VERSIONSTR" >> $GITHUB_ENV

    - shell: pwsh
      run: |
        $USERHOME = "~"
        $USERHOME = ($USERHOME | Resolve-Path |  select -ExpandProperty Path)
        if ($IsWindows -or $ENV:OS) {
          $USERHOME = ($USERHOME -replace '\\', '\\')
        }
        echo "USERHOME=$USERHOME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
