name: setup some useful env duing the build
description: detect and setup env $BUILD_NUMBER, $BRANCH

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        REF=${GITHUB_REF##*/}
        BRANCH="${{env.BRANCH}}"
        BRANCH=${BRANCH:-${REF}}
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV

        BUILD_NUMBER="${{env.BUILD_NUMBER}}"
        [ -z "$BUILD_NUMBER" ] && BUILD_NUMBER=${{github.run_number}}
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

    - shell: powershell
      run: |
        &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
