name: setup go-jira execuable binary
description: >
  download and setup config for go-jira command.
  export $JIRA - exec binary path
  generate default config to ".github/tools/go-jira" if input "use-default = true"

inputs:
  jirad:
    required : true
    description: folder where ".jira.d" is copied to

runs :
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-darwin-amd64"
        $EXT = ""
        if ($IsWindows -or $ENV:OS) {
          $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-windows-amd64.exe"
          $EXT = ".exe"
        }

        $ROOT = "./.github/tools/go-jira"
#        New-Item -Path "$ROOT" -Force
#        $ROOT = ($ROOT | Resolve-Path |  select -ExpandProperty Path)
#        echo "root= $ROOT"

        $JIRA = "$ROOT/jira$EXT"
        New-Item -Path "$JIRA" -Force
        Invoke-WebRequest $GO_JIRA_URL -OutFile $JIRA
        $JIRA = ($JIRA | Resolve-Path |  select -ExpandProperty Path)

        chmod +x $JIRA
        echo "JIRA=$JIRA" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: create custom command config
      shell: bash
      run: |
#        JIRAD="${{inputs.jirad}}"
#        mkdir -p $JIRAD
        echo "copy go-jira config to ${{env.USERHOME}}"
        cp -Rf "${{github.action_path}}/conf/.jira.d" "${{env.USERHOME}}"

    - name: ">> test"
      shell: bash
      run: |
        $JIRA version
        ls -all -R "${{env.USERHOME}}"
