name: setup verNumber and buildNumber
description: detect and setup env $BUILD_NUMBER, $BRANCH

inputs:
  branch:
    required : false
    description: missing = event.branch
  build-number:
    required : false
    description: missing = github.run_number

runs :
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-darwin-amd64"
        $EXT = ""
        if ($IsWindows -or $ENV:OS) {
          $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-windows-amd64.exe"
          $EXT = ".exe"
        }

        $JIRA = "./.github/tools/jira$EXT"
        Invoke-WebRequest $GO_JIRA_URL -OutFile $JIRA

        echo "JIRA=$JIRA" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - shell: bash
      run: $JIRA
