name: setup go-jira execuable binary
description: >
  download and setup config for go-jira command.
  export $JIRA - exec binary path
  generate default config to ".github/tools/go-jira" if input "use-default = true"

#inputs:
#  use-jirad-defaults:
#    required : false
#    default: 'true'
#    description: "true" generate default config ".jira.d" for go-jira to "tools"

runs :
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-darwin-amd64"
        $EXT = ""
        if ($IsWindows -or $ENV:OS) {
          $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-windows-amd64.exe"
          $EXT = ".exe"
        }

        $ROOT = ".github/tools/go-jira"

        $JIRA = "$ROOT/jira$EXT"
        Invoke-WebRequest $GO_JIRA_URL -OutFile (New-Item -Path "$JIRA" -Force)

        chmod +x $JIRA
        echo "JIRA=$JIRA" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        echo "export go-jira config"
        Copy-Item -Path "${{github.action_path}}/conf/*" -Destination "$ROOT/" -Recurse

    - name: ">> test"
      shell: bash
      run: |
        $JIRA version
        ls -all .github/tools/go-jira -R
