name: setup go-jira execuable binary
description: >
  download and setup config for go-jira command.
  export $JIRA - exec binary path
  generate default config to ".github/tools/go-jira" if input "use-default = true"

inputs:
  jirad:
    required : true
    description: folder where ".jira.d" is copied to

runs :
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-darwin-amd64"
        $EXT = ""
        if ($IsWindows -or $ENV:OS) {
          $GO_JIRA_URL = "https://github.com/go-jira/jira/releases/download/v1.0.27/jira-windows-amd64.exe"
          $EXT = ".exe"
        }

        $ROOT = ".github/tools/go-jira"

        $JIRA = "$ROOT/jira$EXT"
        Invoke-WebRequest $GO_JIRA_URL -OutFile (New-Item -Path "$JIRA" -Force)

        chmod +x $JIRA
        echo "JIRA=$JIRA" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        $JIRAD = "${{inputs.jirad}}"
        New-Item -Path "$JIRAD" -Force
        echo "export go-jira config to $JIRAD"
        Copy-Item -Path "${{github.action_path}}/.jira.d" -Destination "$JIRAD" -Recurse

    - name: ">> test"
      shell: bash
      run: |
        $JIRA version
        ls -all ${{inputs.jirad}} -R
