name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

runs:
  using: "composite"
  steps:
    - name: export sign cert pfx file
      shell: bash
      working-directory: .github/tools
      run: |
        echo "${{env.WIN_CODESIGN_BASE64}}" > wincodesign.b64

        $SIGNTOOL_B64="wincodesign.b64"
        $SIGNTOOL_PFX="wincodesign.pfx"

        certutil -decode $SIGNTOOL_B64 $SIGNTOOL_PFX
        certutil -f -user -p "${{env.WIN_CODESIGN_PASSWORD}}" -importpfx $SIGNTOOL_PFX NoRoot

        $SIGNTOOL_PFX=(Resolve-Path -Path $SIGNTOOL_PFX | foreach { $_.Path })
        echo "SIGNTOOL_PFX=$SIGNTOOL_PFX" >> $GITHUB_ENV
