#inputs:
#  name:
#    description: 'Your name'
#    default: 'No name provided'

name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

runs:
  using: "composite"
  steps:
    - name: detect signtool.exe
      shell: cmd
      working-directory: .github/
      run: |
        ${{github.action_path}}\signtool_exe.bat
        echo %SIGNTOOL_EXE%

    - name: debug
      shell: bash
      run: |
        echo ${{env.SIGNTOOL_EXE}}
