#inputs:
#  name:
#    description: 'Your name'
#    default: 'No name provided'

name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

runs:
  using: "composite"
  steps:
    - name: detect signtool.exe
      shell: powershell
      id: detect_signtool_exe
      run: |
        Invoke-Item ${{github.action_path}}\signtool_exe.bat
        echo $SIGNTOOL_EXE
        echo "SIGNTOOL_EXE=$SIGNTOOL_EXE" >> $GITHUB_ENV

#    - name: set env
#      shell: bash
#      run: |
#        echo "debug: ${{steps.detect_signtool_exe.outputs.SIGNTOOL_EXE}}"
#        SIGNTOOL_EXE=${{steps.detect_signtool_exe.outputs.SIGNTOOL_EXE}}
#        echo "debug: SIGNTOOL_EXE=${{steps.detect_signtool_exe.outputs.SIGNTOOL_EXE}}"
#        echo 'SIGNTOOL_EXE="${SIGNTOOL_EXE}"' >> $GITHUB_ENV

    - name: debug
      shell: bash
      run: |
        echo "SIGNTOOL_EXE=${{env.SIGNTOOL_EXE}}"
