#inputs:
#  name:
#    description: 'Your name'
#    default: 'No name provided'

name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

runs:
  using: "composite"
  steps:
    - name: detect signtool.exe
      shell: cmd
      id: detect_signtool_exe
      run: |
        ${{github.action_path}}\signtool_exe.bat
        echo %SIGNTOOL_EXE%
        echo "::set-output name=SIGNTOOL_EXE::%SIGNTOOL_EXE%"

    - name: set env
      shell: bash
      run: |
        SIGNTOOL_EXE=${{steps.detect_signtool_exe.outputs.SIGNTOOL_EXE}}
        echo 'SIGNTOOL_EXE="${SIGNTOOL_EXE}"' >> $GITHUB_ENV

    - name: debug
      shell: bash
      run: |
        echo "SIGNTOOL_EXE=${{env.SIGNTOOL_EXE}}"
