name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

inputs:
  WIN_CODESIGN_BASE64:
    description: windows codesign in base64
    required: false

runs:
  using: "composite"
  steps:
    - name: export sign cert pfx file
      shell: bash
      working-directory: .github
      run: |
        echo "${{ inputs.WIN_CODESIGN_BASE64 }}" > wincodesign.b64
        echo "SIGNTOOL_PFX=hello-me" >> $GITHUB_ENV
