#inputs:
#  name:
#    description: 'Your name'
#    default: 'No name provided'

name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

runs:
  using: "composite"
  steps:
    - name: detect signtool.exe
      shell: bash
      run: |
        node ${{github.action_path}}/getSigntool.js

#    - name: debug
#      shell: bash
#      run: |
#        echo 123
#        echo ${{steps.signtool_exe.outputs.SIGNTOOL_EXE}}
#        signtool xxx
