#inputs:
#  name:
#    description: 'Your name'
#    default: 'No name provided'

name: detect signtool.exe
description: auto detect signtool.exe installed in GHA windows runner

runs:
  using: "composite"
  steps:
    - name: detect signtool.exe
      shell: cmd
      id: signtool_exe
      run: |
        ${{github.action_path}}\signtool_exe.bat
        echo %SIGNTOOL_EXE%
        echo ::set-output name=SIGNTOOL_EXE::green

    - name: debug
      shell: bash
      run: |
        echo 123
        echo ${{steps.signtool_exe.outputs.SIGNTOOL_EXE}}
        signtool xxx
