project: __JIRA_PROJECT__
endpoint: https://datalocker.atlassian.net
user: phuonghqh@gmail.com
authentication-method: api-token

custom-commands:
  - name: pp
    help: print the name of the configured project
    script: "echo $JIRA_PROJECT"

  - name: att
    help: attact built-atifact to issue {id}
    options:
      - name: id
        help: created issue to upload attifacts
        required: true
      - name: file
        help: upload file locations (repeatable)
        required: true
        repeat: true
    script: |
      ${JIRA} attach create {{range options.file}} {{options.id}} {{.}} {{end}}

#      ${JIRA} attach create {{options.id}} \
#        {{range options.file}} --file {{.}}{{end}}

