endpoint: https://datalocker.atlassian.net
user: phuonghqh@gmail.com
authentication-method: api-token

custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          ${JIRA} list --template table --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
          # otherwise list issues for all project
          ${JIRA} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
