name: setup verNumber and buildNumber
description: detect and setup env $BUILD_NUMBER, $BRANCH

inputs:
  branch:
    required : false
    description: missing = event.branch
  build-number:
    required : false
    description: missing = github.run_number

runs :
  using: "composite"
  steps:
    - name: export sign cert pfx file
      shell: bash
      run: |
        REF=${GITHUB_REF##*/}
        BRANCH="${{github.event.inputs.branch}}"
        BRANCH=${BRANCH:-${REF}}
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
        [ -z "$BUILD_NUMBER" ] && BUILD_NUMBER=${{github.run_number}}
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
