name: build-reuse

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["windows-2016", "macos-10.15"]'
      branch:
        description: 'branch name'
        required: false
        default: 'dev'
      version:
        description: 'release version str (1.0.1)'
        required: false
        default: 0.0.1
      build_number:
        description : 'build number, empty=run_id'
        required : false

env:
  _GITHUB_PAT: ${{secrets._GITHUB_PAT}}
  VER_NUMBER: ${{github.event.inputs.version}}
  BUILD_NUMBER: ${{github.event.inputs.build_number}}
  WIN_CODESIGN_BASE64: ${{secrets.WIN_CODESIGN_BASE64}}
  WIN_CODESIGN_PASSWORD: ${{secrets.WIN_CODESIGN_PASSWORD}}

jobs:
  make-reuse:
    strategy:
      matrix:
        os: ${{fromJson(github.event.inputs.run_ons)}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go-jira
      - name: ">> debug"
        shell: bash
        run: |
          ls -all ./.github/tools
          jira --help
