name: a1

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '[{"os": "windows-2019", "shell": "cmd"}, {"os": "macos-10.15", "shell": "bash"}]'

#["windows-2019", "macos-10.15"]'

env:
  _GITHUB_PAT: ${{secrets._GITHUB_PAT}}
  JIRA_PROJECT: ${{secrets.TEST_JIRA_PROJECT}}
  JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}

jobs:
  make-reuse:
    strategy:
      matrix: ${{fromJson(github.event.inputs.run_ons)}}
#        include:
#          - os: ${{fromJson(github.event.inputs.run_ons)}}

#        strategy:
#          matrix:
#            include:
#              - node-version: 10.x
#                site: "prod"
#                datacenter: "site-a"
#              - node-version: 12.x
#                site: "dev"
#                datacenter: "site-b"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-preclone-env
      - uses: ./.github/actions/setup-go-jira
        with:
          jirad-yml: ./.github/workflow/test/config.yml

      - name: ">> debug"
#        if: runner.os == 'windows'
        shell: ${{matrix.shell}}
        run: |
          ${{env.JIRA}} pp
          ${{env.JIRA}} mine


      - name: ">> debug"
        if: runner.os == 'macOS'
        shell: bash
        run: |
          ${{env.JIRA}} pp
          ${{env.JIRA}} mine
