name: driver

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["windows-2019"]'
      branch:
        description: 'branch name'
        required: false
        default: 'SAFECRYPT-204-auto-unlock'
      version:
        description: 'release version str (1.0.1)'
        required: true
      build_number:
        description : 'build number, empty=run_id'
        required : false

env:
  _GITHUB_PAT: ${{secrets._GITHUB_PAT}}
  VER_NUMBER: ${{github.event.inputs.version}}
  BRANCH: ${{github.event.inputs.branch}}
  BUILD_NUMBER: ${{github.event.inputs.build_number}}
  WIN_CODESIGN_BASE64 : ${{secrets.WIN_CODESIGN_BASE64}}
  WIN_CODESIGN_PASSWORD : ${{secrets.WIN_CODESIGN_PASSWORD}}

jobs:
  msbuild:
    strategy:
      matrix:
        os: ${{fromJson(github.event.inputs.run_ons)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses : actions/checkout@v2
        with :
          submodules : true

      - uses: ./.github/actions/setup-preclone-env
      - uses: ./.github/actions/setup-go-jira

      - name: install win cert for siging
        uses: ./.github/actions/win-install-signing-cert

      - name: ">> debug"
        run: |
          echo "outputs: ${{toJSON(steps.run_gradlew_build.outputs)}}"
          echo "exit-code: ${{steps.run_gradlew_build.outputs.exit_code}}"
