name: a1

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["windows-2019", "macos-10.15"]'

env:
  _GITHUB_PAT: ${{secrets._GITHUB_PAT}}
  JIRA_PROJECT: TestMe
  JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}

jobs:
  make-reuse:
    strategy:
      matrix:
        os: ${{fromJson(github.event.inputs.run_ons)}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-preclone-env
      - uses: ./.github/actions/setup-go-jira
        with:
          project-name: ${{env.JIRA_PROJECT}}

      - name: ">> debug"
        run: |
          ${{env.JIRA}} pp
