name: abc

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["macos-10.15"]'

jobs:
  make_scm_client:
    strategy:
      matrix:
        os: ${{fromJson(github.event.inputs.run_ons)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
          echo "${{github.event_name}}"
