name: a1

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["windows-2019", "macos-10.15"]'

env:
  _GITHUB_PAT: ${{secrets._GITHUB_PAT}}
  JIRA_PROJECT: ${{secrets.TEST_JIRA_PROJECT}}
  JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}

jobs:
  make-reuse:
    strategy:
      matrix: ${{fromJson(github.event.inputs.run_ons)}}

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-preclone-env
      - uses: ./.github/actions/setup-go-jira

      - name: ">> debug"
#        if: runner.os == 'windows'
#        shell: cmd
        run: |
          ${{env.JIRA}} pp
          ${{env.JIRA}} mine


#      - name: ">> debug"
#        if: runner.os == 'macOS'
#        shell: bash
#        run: |
#          ${{env.JIRA}} att --id SCM-228 --file jira.sh --file logger-macOS.zip
