name: driver

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["windows-2019"]'
      branch:
        description: 'branch name'
        required: false
        default: 'PB-1124-GHA-impl'
      version:
        description: 'release version str (1.0.1)'
        default: 1.1.1
        required: true
      build_number:
        description : 'build number, empty=run_id'
        required : false

env:
  _GITHUB_PAT: ${{secrets._GITHUB_PAT}}
  VER_NUMBER: ${{github.event.inputs.version}}
  BRANCH: ${{github.event.inputs.branch}}
  BUILD_NUMBER: ${{github.event.inputs.build_number}}
  WIN_CODESIGN_BASE64 : ${{secrets.WIN_CODESIGN_BASE64}}
  WIN_CODESIGN_PASSWORD : ${{secrets.WIN_CODESIGN_PASSWORD}}
  PBWINDRIVER_REPO : ${{secrets.PBWINDRIVER_REPO}}

jobs:
  msbuild:
    strategy:
      matrix:
        os: ${{fromJson(github.event.inputs.run_ons)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses : actions/checkout@v2
        with :
          submodules : true

#      - name: install win cert for siging
#        uses: ./.github/actions/win-install-signing-cert

      - name: setup ssh
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA_BITBUCKET }}
          name: id_rsa_bitbucket
          known_hosts: $${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}

      - name: clone source
        shell: bash
        run: |
          git clone --single-branch \
             --branch ${{github.event.inputs.branch}} \
             --depth 1 --recurse-submodules \
             ${{env.PBWINDRIVER_REPO}} \
             git

      - name: ">> build"
        working-directory: ./git
        shell: cmd
        run: msbuild
