name: manual-build
on:
  workflow_dispatch:
    inputs:
      os_name:
        description: 'os name'
        required: true
        default: 'windows-2019'

jobs:
  clone_and_build_app:
    runs-on: ${{github.event.inputs.os_name}}

    steps:
      - uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: setup windows-build-tools
        if: runner.os == 'Windows'
        run: npm i -g windows-build-tools --vs2015

      - name: build node native sample
        run: npm i
        working-directory: ./src/test
