name: test workflow

on:
  workflow_dispatch:
    inputs:
      branch_sc_installer:
        description: 'sc_installer branch name'
        required: true
        default: 'dev-tc8'
      branch_emp:
        description: 'emp branch name'
        required: true
        default: 'dev-tc8'
      branch_emp_app:
        description: 'emp_app branch name'
        required: true
        default: 'dev-tc8'

#env:
#  INSTALL4j_DOWNLOAD_URL: https://download-gcdn.ej-technologies.com/install4j/install4j_windows-x64_6_1_6.zip

jobs:
  clone_and_build_app:
    strategy:
      matrix:
        os: [ "windows-2019" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: phuonghuynh/configurator@v0.0.10
        id: setup_install4j
        with:
          url: https://download-gcdn.ej-technologies.com/install4j/install4j_windows-x64_6_1_6.zip

      - name: Testing
        run: |
          echo ${{steps.setup_install4j.outputs.extract_location}}
          dir ${{steps.setup_install4j.outputs.extract_location}}
