name: test workflow

on:
  workflow_dispatch:
    inputs:
      branch_sc_installer:
        description: 'sc_installer branch name'
        required: true
        default: 'dev-tc8'
      branch_emp:
        description: 'emp branch name'
        required: true
        default: 'dev-tc8'
      branch_emp_app:
        description: 'emp_app branch name'
        required: true
        default: 'dev-tc8'

env:
  INSTALL4J_LICENSE: ${{secrets.INSTALL4J_LICENSE}}
  SC_INSTALLER_HOME: ./git/sc-installer
  EMP_HOME: ./git/emp
  EMPAPP_HOME: ./git/empApp

jobs:
  clone_and_build_app:
    strategy:
      matrix:
        os: [ "windows-2019" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: setup nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10
      - uses: actions/setup-java@v1
        with:
          java-version: 8.0.252
          java-package: jdk
          architecture: x64

      - uses: actions/checkout@v2
        with:
          repository: dlsecure/sc-installer
          path: ${{env.SC_INSTALLER_HOME}}
          ref: ${{github.event.inputs.branch_sc_installer}}
          submodules: false
      - uses: actions/checkout@v2
        with:
          repository: dlsecure/emp
          path: ${{env.EMP_HOME}}
          ref: ${{github.event.inputs.branch_emp}}
          submodules: false
      - uses: actions/checkout@v2
        with:
          repository: dlsecure/empApp
          path: ${{env.EMPAPP_HOME}}
          ref: ${{github.event.inputs.branch_emp_app}}
          submodules: false

      - name: setup install4j
        uses: phuonghuynh/configurator@v0.0.10
        id: setup_install4j
        with:
          url: https://download-gcdn.ej-technologies.com/install4j/install4j_windows-x64_6_1_6.zip

      - name: setup env
        run: |
          echo "INSTALL4J_HOME=${{steps.setup_install4j.outputs.extract_location}}/install4j6.1.6" >> $GITHUB_ENV
