name: test2

on:
  workflow_dispatch:
    inputs:
      branch_sc_installer:
        description: 'sc_installer branch name'
        required: true
        default: 'dev-tc8'
      branch_emp:
        description: 'emp branch name'
        required: true
        default: 'dev-tc8'
      branch_emp_app:
        description: 'emp_app branch name'
        required: true
        default: 'dev-tc8'

env:
  INSTALL4J_LICENSE: ${{secrets.INSTALL4J_LICENSE}}


jobs:
  build-sc-installer:
    strategy:
      matrix:
        os: [ "windows-2019" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: setup java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8.0.252
          java-package: jdk
          architecture: x64

      - name: setup env
        shell: bash
        run: |
          echo "INSTALL4J_HOME=${{steps.setup_install4j.outputs.extract_location}}/install4j6.1.6" >> $GITHUB_ENV

          echo "SC_INSTALLER_HOME=./git/sc-installer" >> $GITHUB_ENV
          echo "EMP_HOME=./git/emp" >> $GITHUB_ENV
          echo "EMPAPP_HOME=./git/empApp" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: dlsecure/sc-installer
          path: ${{env.SC_INSTALLER_HOME}}
          ref: ${{github.event.inputs.branch_sc_installer}}
          submodules: false

      - name: build sc-installer
        run: >
          echo ${{env.SC_INSTALLER_HOME}}

      - name: archive installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: ${{env.SC_INSTALLER_HOME}}/target/installer
