name: sc-installer

on:
  workflow_dispatch:
    inputs:
      run_ons:
        description: 'OS list'
        required: true
        default: '["windows-2019", "macos-10.15"]'
      branch:
        description: 'branch name'
        required: true
        default: 'SCM-209_grpc_ssl_expiration'

env:
  _GITHUB_PAT: "${{secrets._GITHUB_PAT}}"

jobs:
  test-build:
    strategy:
      matrix:
        os: ${{fromJson(github.event.inputs.run_ons)}}
    runs-on: ${{matrix.os}}

    steps:
      - name: clone source
        uses: actions/checkout@v2
        with:
          repository: dlsecure/safecrypt-service
          token: ${{env._GITHUB_PAT}}
          ref: ${{github.event.inputs.branch}}
          path: git
          submodules: true

      - name: setup mac env
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "JDK_URL=https://www.dropbox.com/s/3tvg40lwuivyaek/mac-jdk-9.0.4.zip?dl=1" >> $GITHUB_ENV
          JAVA_HOME="${GITHUB_WORKSPACE}/tools/jdk-9.0.4.jdk/Contents/Home"
          echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "${JAVA_HOME}/bin" >> $GITHUB_PATH

      - name: setup win env
        if: runner.os == 'windows'
        shell: bash
        run: |
          echo "JDK_URL=https://www.dropbox.com/s/z1sh0shlfrdacsl/win-jdk-9.0.4.zip?dl=1" >> $GITHUB_ENV
          JAVA_HOME=${GITHUB_WORKSPACE}\\tools\\jdk-9.0.4
          echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "$JAVA_HOME\\bin" >> $GITHUB_PATH

      - name: setup win path env
        if: runner.os == 'windows'
        run: |
          echo "$env:JAVA_HOME\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: download
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{env.JDK_URL}}
          target: ./tools/

      - name: extract jdk
        working-directory: ./tools
        run: |
          7z x *.zip
          echo $JAVA_HOME
          java -version
