name: sc-installer

on:
  workflow_dispatch:
    inputs:
      branch_sc_installer:
        description: 'sc_installer branch name'
        required: true
        default: 'dev-tc8'
      branch_emp:
        description: 'emp branch name'
        required: true
        default: 'dev-tc8'
      branch_emp_app:
        description: 'emp_app branch name'
        required: true
        default: 'dev-tc8'

env:
  INSTALL4J_LICENSE: ${{secrets.INSTALL4J_LICENSE}}


jobs:
  build-sc-installer:
    strategy:
      matrix:
        os: [ "macos-10.15" ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: download
        uses: suisei-cn/actions-download-file@v1
        with:
          url: https://www.dropbox.com/s/z1sh0shlfrdacsl/mac-jdk-9.0.4.zip?dl=1
          target: ./tools/

      - name: extract jdk
        working-directory: ./tools
        run: |
          7z x *.zip
          ls -all .
